[colors.bright]
black = "0x4c566a"
blue = "0x5e81ac"
cyan = "0x8fbcbb"
green = "0x8fbcbb"
magenta = "0xd08770"
red = "0xa1a1aa"
white = "0xffffff"
yellow = "0xe0e0e0"

[colors.normal]
black = "0x3b4252"
blue = "0x81a1c1"
cyan = "0x88c0d0"
green = "0xa3be8c"
magenta = "0xb48ead"
red = "0xbf616a"
white = "0xe5e9f0"
yellow = "0xebcb8b"

[colors.primary]
background = "0x2e3440"
foreground = "0xd8dee9"

[env]
COLORTERM = "truecolor"
TERM = "xterm-256color"

[font]
normal = { family = "FiraMono Nerd Font", style = "Regular" }
bold = { family = "FiraMono Nerd Font", style = "Bold" }
italic = { family = "FiraMono Nerd Font", style = "Italic" }
size = 9.0
